# Generated by Django 5.1.5 on 2026-01-25 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoBayApp', '0002_alter_category_id_alter_item_id_alter_offer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='name',
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EcoBayApp.item'),
            preserve_default=False,
        ),
    ]
