# Generated by Django 5.1.5 on 2026-01-27 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoBayApp', '0003_remove_item_created_at_remove_offer_name_offer_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 27, 18, 44, 15, 841796, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
